<div class="span6">
	<!--BEGIN TABS-->
	<div class="tabbable tabbable-custom tabs-left">
		<!-- Only required for left/right tabs -->
		<ul class="nav nav-tabs tabs-left">
			<li class="active"><a href="#tab_3_1" data-toggle="tab">Section 1</a></li>
			<li ><a href="#tab_3_2" data-toggle="tab">Section 2</a></li>
			<li><a href="#tab_3_3" data-toggle="tab">Section 3</a></li>
		</ul>
		<div class="tab-content">
			<div class="tab-pane active" id="tab_3_1">
				<p>I'm in Section 1. Less content here</p>
			</div>
			<div class="tab-pane " id="tab_3_2">
				<p>Howdy, I'm in Section 2.</p>
				<p>
					Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat. 
				</p>
				<p>
					<a  class="btn blue" href="ui_tabs_accordions.html#tab_3_2" target="_blank">Activate this tab via URL</a> 
				</p>
			</div>
			<div class="tab-pane" id="tab_3_3">
				<p>Howdy, I'm in Section 3.</p>
				<p>
					Less content here. 
				</p>
				<p>
					<a class="btn green" href="ui_tabs_accordions.html#tab_3_3" target="_blank">Activate this tab via URL</a>
				</p>
			</div>
		</div>
	</div>
	<!--END TABS-->
</div>

